---
name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: codekoala/test-image:latest
