---
name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/build-push-action@v5
        with:
          network: host
          build-args: |
            POSTGRES_HOST=localhost
            POSTGRES_PORT=5432
            POSTGRES_PASSWORD=postgres
          no-cache: true
          push: false
          tags: codekoala/test-image:latest
